# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift

before_install:
  - brew outdated xctool || brew upgrade xctool
  - travis_wait carthage bootstrap --platform iOS

script:
  - xcodebuild -project "Vandelay.xcodeproj" -scheme "Vandelay" -sdk "iphonesimulator" | xcpretty -c
  - fastlane test